package com.example.data.config

import android.util.Log
import com.example.BuildConfig

/**
 * Production-ready centralized API key provider for Google Cloud and Google Maps Platform services.
 * Integrates securely with BuildConfig generated by secrets-gradle-plugin from .env and local.properties.
 */
object ApiKeyProvider {

    private const val TAG = "ApiKeyProvider"

    /**
     * Primary Google Cloud API key used for Cloud Vision, Places API, and related endpoints.
     */
    val googleCloudApiKey: String
        get() {
            val key = try {
                BuildConfig.GOOGLE_CLOUD_API_KEY
            } catch (e: Exception) {
                ""
            }
            return sanitizeKey(key)
        }

    /**
     * Google Maps Platform API key used for Google Maps SDK and Location services.
     */
    val mapsApiKey: String
        get() {
            val key = try {
                BuildConfig.MAPS_API_KEY
            } catch (e: Exception) {
                ""
            }
            val sanitized = sanitizeKey(key)
            return if (sanitized.isNotEmpty()) sanitized else googleCloudApiKey
        }

    /**
     * Gemini AI API key used for Multimodal Vision, Diagnostics, and LLM services.
     */
    val geminiApiKey: String
        get() {
            val key = try {
                BuildConfig.GEMINI_API_KEY
            } catch (e: Exception) {
                ""
            }
            return sanitizeKey(key)
        }

    /**
     * Checks if a valid Google Cloud API key is present.
     */
    fun isKeyConfigured(): Boolean {
        val key = googleCloudApiKey
        return key.isNotEmpty() && !key.contains("YOUR_") && !key.contains("PLACEHOLDER")
    }

    /**
     * Returns a masked version of the API key for safe debugging without exposing secrets.
     */
    fun getMaskedKey(): String {
        val key = googleCloudApiKey
        return if (key.length >= 8) {
            "${key.take(4)}...${key.takeLast(4)}"
        } else if (key.isNotEmpty()) {
            "***"
        } else {
            "NOT_CONFIGURED"
        }
    }

    private fun sanitizeKey(key: String?): String {
        if (key == null) return ""
        val trimmed = key.trim().trim('"', '\'')
        return if (trimmed.equals("null", ignoreCase = true)) "" else trimmed
    }
}
